#!groovy

// Generated by IBM TransformationAdvisor
// Wed Feb 27 07:28:32 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'bookmydoc'
    mvnCommands = '--version'
    test='false'
}